# Generated by Django 3.1.3 on 2020-11-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=60)),
                ('project_description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('project_link', models.CharField(max_length=60)),
            ],
        ),
    ]
